#!/usr/bin/env python3
"""Run the accepted single-path material frontend for one reconstructed room.

The room name, face names, material count, and room shape never participate in
any decision.  Lab is used only to propose spatial regions.  Material identity
comes from MatSeg descriptors measured in reverse-projected source images, with
the contact-sheet descriptor used only for the explicitly documented
two-singleton ambiguity.  Every selected material is then regenerated by the
maximum-projection-mass v3b source-image trace-back path.
"""

from __future__ import annotations

import argparse
import json
import subprocess
import sys
from pathlib import Path


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser()
    parser.add_argument("--metadata", type=Path, required=True)
    parser.add_argument("--region-assets-dir", type=Path, required=True)
    parser.add_argument("--vendor-dir", type=Path, required=True)
    parser.add_argument("--checkpoint", type=Path, required=True)
    parser.add_argument("--output-dir", type=Path, required=True)
    parser.add_argument("--device", default="cuda:0")
    parser.add_argument(
        "--frontend-dir",
        type=Path,
        default=Path(__file__).resolve().parent / "frontend_v3",
    )
    return parser.parse_args()


def run(command: list[str], log: Path | None = None) -> None:
    if log is None:
        subprocess.run(command, check=True)
        return
    log.parent.mkdir(parents=True, exist_ok=True)
    with log.open("w", encoding="utf-8") as stream:
        subprocess.run(command, check=True, stdout=stream, stderr=subprocess.STDOUT)


def faces(metadata: Path) -> list[str]:
    value = json.loads(metadata.read_text(encoding="utf-8"))
    return [str(record["face"]) for record in value["stats"]]


def unresolved_faces(metadata: Path) -> list[str]:
    value = json.loads(metadata.read_text(encoding="utf-8"))
    return [
        str(record["face"])
        for record in value["stats"]
        if int(record.get("material_count", 1)) > 1
    ]


def trace(
    python: str,
    frontend: Path,
    identity_metadata: Path,
    region_assets: Path,
    package_dir: Path,
    output_metadata: Path,
    trace_log: Path,
    log: Path,
) -> None:
    run(
        [
            python,
            str(frontend / "regenerate_matseg_material_chord_inputs_by_traceback.py"),
            "--identity-metadata",
            str(identity_metadata),
            "--region-assets-dir",
            str(region_assets),
            "--package-dir",
            str(package_dir),
            "--output-metadata",
            str(output_metadata),
            "--trace-log",
            str(trace_log),
            "--generator-script",
            str(frontend / "generate_chord_view_contributor_region_priors.py"),
            "--geometry-fallback-generator-script",
            str(
                frontend
                / "legacy_geometry_fallback"
                / "generate_chord_view_contributor_region_priors.py"
            ),
            "--strict-observed-support-only",
            "--skip-untraceable-materials",
        ],
        log,
    )


def main() -> int:
    args = parse_args()
    frontend = args.frontend_dir.resolve()
    output = args.output_dir.resolve()
    output.mkdir(parents=True, exist_ok=True)
    python = sys.executable

    preidentity_dir = output / "preidentity"
    preidentity_metadata = preidentity_dir / "metadata.json"
    preidentity_receipt = preidentity_dir / "receipt.json"
    run(
        [
            python,
            str(frontend / "filter_incoherent_material_groups.py"),
            "--metadata",
            str(args.metadata),
            "--region-assets-dir",
            str(args.region_assets_dir),
            "--output",
            str(preidentity_metadata),
            "--receipt",
            str(preidentity_receipt),
        ],
        preidentity_dir / "run.log",
    )

    original_reports = output / "original_view_reports"
    contact_root = output / "contact_reports"
    # Descriptor extraction must read the original unified proposal package,
    # because that package owns the support masks and rectified assets.  The
    # prefiltered metadata is used only by the identity resolver below, which
    # subsets these complete descriptor matrices by surviving region id.
    for face in unresolved_faces(preidentity_metadata):
        run(
            [
                python,
                str(frontend / "run_matseg_material_identity_from_v3b_regions.py"),
                "--metadata",
                str(args.metadata),
                "--vendor-dir",
                str(args.vendor_dir),
                "--checkpoint",
                str(args.checkpoint),
                "--output-dir",
                str(original_reports / face),
                "--face",
                face,
                "--max-side",
                "700",
                "--views-per-region",
                "3",
                "--similarity-threshold",
                "0.87",
                "--device",
                args.device,
            ],
            original_reports / face / "run.log",
        )
        run(
            [
                python,
                str(frontend / "run_matseg_material_identity_contact.py"),
                "--metadata",
                str(args.metadata),
                "--vendor-dir",
                str(args.vendor_dir),
                "--checkpoint",
                str(args.checkpoint),
                "--output-dir",
                str(contact_root / "reports" / face),
                "--face",
                face,
                "--device",
                args.device,
            ],
            contact_root / "reports" / face / "run.log",
        )

    identity_dir = output / "identity"
    identity_metadata = identity_dir / "metadata_matseg_identity.json"
    identity_receipt = identity_dir / "identity_receipt.json"
    run(
        [
            python,
            str(frontend / "resolve_original_view_matseg_identity.py"),
            "--metadata",
            str(preidentity_metadata),
            "--original-view-reports-root",
            str(original_reports),
            "--contact-reports-root",
            str(contact_root),
            "--output",
            str(identity_metadata),
            "--reports-output-dir",
            str(identity_dir / "reports"),
            "--receipt",
            str(identity_receipt),
        ],
        identity_dir / "run.log",
    )

    first_trace = output / "first_trace"
    trace(
        python,
        frontend,
        identity_metadata,
        args.region_assets_dir,
        first_trace / "package",
        first_trace / "metadata.json",
        first_trace / "trace.json",
        first_trace / "run.log",
    )

    recovered = output / "recovered"
    recovered_metadata = recovered / "metadata.json"
    run(
        [
            python,
            str(frontend / "recover_untraceable_structural_support_by_matseg.py"),
            "--identity-metadata",
            str(identity_metadata),
            "--first-trace-metadata",
            str(first_trace / "metadata.json"),
            "--original-view-reports-root",
            str(original_reports),
            "--contact-reports-root",
            str(contact_root),
            "--output",
            str(recovered_metadata),
            "--receipt",
            str(recovered / "receipt.json"),
        ],
        recovered / "run.log",
    )

    recovered_trace = output / "recovered_trace"
    trace(
        python,
        frontend,
        recovered_metadata,
        args.region_assets_dir,
        recovered_trace / "package",
        recovered_trace / "metadata.json",
        recovered_trace / "trace.json",
        recovered_trace / "run.log",
    )

    native_guard = output / "native_scale_guard"
    guarded_metadata = native_guard / "metadata.json"
    run(
        [
            python,
            str(frontend / "filter_incoherent_material_groups.py"),
            "--metadata",
            str(recovered_trace / "metadata.json"),
            "--region-assets-dir",
            str(args.region_assets_dir),
            "--output",
            str(guarded_metadata),
            "--receipt",
            str(native_guard / "receipt.json"),
        ],
        native_guard / "run.log",
    )

    final_trace = output / "final_trace"
    final_metadata = final_trace / "metadata_final_traceback_inputs.json"
    final_trace_log = final_trace / "material_level_traceback.json"
    trace(
        python,
        frontend,
        guarded_metadata,
        args.region_assets_dir,
        final_trace / "package",
        final_metadata,
        final_trace_log,
        final_trace / "run.log",
    )

    summary = {
        "method": "v3b_v3_unified_original_view_matseg_traceback_frontend",
        "room_or_material_profile_used": False,
        "material_identity_source": "MatSeg only",
        "proposal_source": str(args.metadata.resolve()),
        "identity_receipt": str(identity_receipt),
        "recovery_receipt": str(recovered / "receipt.json"),
        "native_scale_guard_receipt": str(native_guard / "receipt.json"),
        "final_metadata": str(final_metadata),
        "final_trace_log": str(final_trace_log),
        "final_package_dir": str(final_trace / "package"),
    }
    (output / "frontend_summary.json").write_text(
        json.dumps(summary, indent=2, ensure_ascii=False) + "\n", encoding="utf-8"
    )
    print(json.dumps(summary, indent=2, ensure_ascii=False))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
